### ISSUE TITLE
InvalidNameError - Input field does not accpet tag string 

### ISSUE THREAD

**Issue by ByunghoJeon** [jmcarp/robobrowser#29]
I found that robobrowser can add form field dynamically like this:

```python
browser = RoboBrowser(history=True)
myform = browser.get_form('myform2')
new_field = Input('\<input name="myname" value="" \/\>')
myform.add_field( new_field )
```

But InvalidNameError occured in Input class.

## RoboBrowser's Input Field occurred InvalidNameError
```python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> from robobrowser.forms.fields import Input
>>> Input('<input name="myfield" value=""/>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/robobrowser/forms/fields.py", line 72, in __init__
    super(Input, self).__init__(parsed)
  File "/usr/local/lib/python2.7/dist-packages/robobrowser/forms/fields.py", line 46, in __init__
    self.name = self._get_name(self._parsed)
  File "/usr/local/lib/python2.7/dist-packages/robobrowser/forms/fields.py", line 52, in _get_name
    raise exceptions.InvalidNameError
robobrowser.exceptions.InvalidNameError
>>> 
```
## Packages version
```
$ pip search robobrowser
robobrowser               - Your friendly neighborhood web scraper
  INSTALLED: 0.5.1 (latest)
$ pip search beautifulsoup
beautifulsoup4            - Screen-scraping library
  INSTALLED: 4.3.2 (latest)
BeautifulSoup             - HTML/XML parser for quick-turnaround applications like screen-scraping.
  INSTALLED: 3.2.1 (latest)
```

**Comment by jmcarp** [comment]
I believe this issue was fixed in eee0cd8007460862b239c1ba7ae101c6e745a736 by @pratyushmittal, so installing version 0.5.2 should take care of this.
