### ISSUE TITLE
Import Error: HTMLParser

### ISSUE THREAD

**Issue by vorticalbox** [jmcarp/robobrowser#80]
When importing robobrowser, from robobrowser import RoboBrowser on windows 10 I am getting 

ImportError: cannot import name 'HTMLParseError'

full error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\vorti\AppData\Local\Programs\Python\Python36-32\lib\site-packages\robobrowser\__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "C:\Users\vorti\AppData\Local\Programs\Python\Python36-32\lib\site-packages\robobrowser\browser.py", line 7, in <module>
    from bs4 import BeautifulSoup
  File "C:\Users\vorti\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Users\vorti\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bs4\builder\__init__.py", line 308, in <module>
    from . import _htmlparser
  File "C:\Users\vorti\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bs4\builder\_htmlparser.py", line 7, in <module>
    from html.parser import (
ImportError: cannot import name 'HTMLParseError'

**Comment by vorticalbox** [comment]
Turns out BS$ was broken on my windows so not an issue
