### ISSUE TITLE
RoboBrowser is broken with werkzeug upgrade

### ISSUE THREAD

**Issue by TijanaJakovljevic** [jmcarp/robobrowser#93]
werkzeug is upgraded to 1.0.0 and RoboBrowser is broken with this change. 
```
Traceback (most recent call last):
     from robobrowser import RoboBrowser
   File "/home/ubuntu/venv/lib/python3.7/site-packages/robobrowser/__init__.py", line 3, in <module>
     from .browser import RoboBrowser
   File "/home/ubuntu/venv/lib/python3.7/site-packages/robobrowser/browser.py", line 8, in <module>
     from werkzeug import cached_property
 ImportError: cannot import name 'cached_property' from 'werkzeug' (/home/ubuntu/venv/lib/python3.7/site-packages/werkzeug/__init__.py)
```

It’s because cached_property has to be explicitly imported from werkzeug.utils now
 'from werkzeug.utils import cached_property' should be used instead 'from werkzeug import cached_property'

**Comment by H3wastooshort** [comment]
made it a prq @ #97

**Comment by manishmaharjan** [comment]
I had a similar issue. 

`import werkzeug`
`werkzeug.cached_property = werkzeug.utils.cached_property`

adding this before `import robobrowser `solved the issue for me

**Comment by j4nr6n** [comment]
You can downgrade Wekzeug until RoboBrowser is fixed. 
`pip install Werkzeug==0.16.1`

**Comment by lovetoburnswhen** [comment]
> I had a similar issue.
> 
> `import werkzeug`
> `werkzeug.cached_property = werkzeug.utils.cached_property`
> 
> adding this before `import robobrowser `solved the issue for me

Worked for me as well thanks

**Comment by Swastik1620** [comment]
ModuleNotFoundError: No module named 'pandas.util'
